trigger:

- master

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: invictustest
      type: git
      name: invictustest/invictustest
      ref: refs/heads/main


steps:
- checkout: invictustest

