jobs:
  netspaker_scan_job:
    runs-on: ubuntu-20.04
    steps:
      # Starts actions with given inputs
      - name: Start Netsparker Enterprise Scan
        uses: netsparker/Netsparker-Cloud-GitHub-Actions@v0.1.0
        id: netsparker-enterprise-scan-step
        with:
          website-id: '368262f0-2ea4-4704-6060-af4903b41d5d'
          scan-type: 'FullWithSelectedProfile'
          profile-id: 'd2b74f68-2d75-4be7-a982-af4903b45518'
          user-id: 'bdb3e6e42e8d4cd53ff8ae5801fec208'
          api-token: 'fIT+6HKMO3oio0QbIUYbi3GLq3DTHPv4/FrTZt438zY='
          base-url: 'https://www.netsparkercloud.com'
      # Displays output for action
      - name: Display Scan Request Message
        run: echo "${{ steps.netsparker-enterprise-scan-step.outputs.scan-message }}"
