name: Cachix
on:
  push:
    branches:
      - master

jobs:
  netsparker_scan_job:
    runs-on: ubuntu-20.04
    steps:
    - name: Run Bash Script
      run: |
        #!/bin/bash

        echo "Hello, World!"
        MinimumSeverity='Critical,High' 
        CancelScan=false
